# Generated by Django 5.1.4 on 2025-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=20)),
                ('emoji', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=7)),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('text_entry', models.TextField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
