# Generated by Django 5.1.4 on 2025-09-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodiary',
            name='mood',
            field=models.CharField(choices=[('😁元気', '😁 元気'), ('😢悲しい', '😢 悲しい'), ('😐普通', '😐 普通')], max_length=20),
        ),
    ]
