# Generated by Django 5.1.4 on 2025-09-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_audiodiary_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodiary',
            name='mood',
            field=models.CharField(choices=[('😁元気', '😁 元気'), ('😢悲しい', '😢 悲しい'), ('😐普通', '😐 普通'), ('😍嬉しい', '😍 嬉しい'), ('😎かっこいい', '😎 かっこいい'), ('😴眠い', '😴 眠い'), ('🤔考え中', '🤔 考え中'), ('😇幸せ', '😇 幸せ'), ('😡怒り', '😡 怒り'), ('🥳お祝い', '🥳 お祝い'), ('😱びっくり', '😱 びっくり'), ('🤯やばい', '🤯 やばい'), ('🤗感謝', '🤗 感謝'), ('😤やる気', '😤 やる気'), ('その他', 'その他')], max_length=20),
        ),
    ]
